---
- name: Ensure package is installed
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: present
  loop: "{{ alternative_packages }}"
- name: Ensure packages present and set alternatives
  community.general.alternatives:
    name: "{{ item.name | default(item) }}"
    link: "{{ item.link | default(link) }}"
    path: "{{ item.path | default(path) }}"
    state: selected
  loop: "{{ alternative_packages }}"
