---
- name: Ensure package is installed
  ansible.builtin.dnf:
    name: "{{ item.package }}"
  loop: "{{ alternative_packages }}"

- name: Ensure packages present and set alternatives
  community.general.alternatives:
    name: "{{ item.name }}"
    link: "{{ item.link }}"
    path: "{{ item.path }}"
    state: auto
  loop: "{{ alternative_packages }}"
